<?php

namespace AppBundle\Repository;

/**
 * QCMsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMsRepository extends \Doctrine\ORM\EntityRepository
{

    function getQCM()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->setFirstResult(0);
        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
