<?php

namespace AppBundle\Repository;

/**
 * QCMsQuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMsQuestionsRepository extends \Doctrine\ORM\EntityRepository
{

}
