# Login
fos_user_security_login:
    path:      /login
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:      /login_check
    defaults:  { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:      /logout
    defaults:  { _controller: FOSUserBundle:Security:logout }

# Registration
fos_user_registration_register:
    path:      /inscription
    defaults: { _controller: FOSUserBundle:Registration:register }
    methods:
        - GET
        - POST